splash = false

preload = ~/.config/backgrounds/background_laptop.png
preload = ~/.config/backgrounds/background_left.png
preload = ~/.config/backgrounds/background_right.png

wallpaper {
    monitor = eDP-1
    path = ~/.config/backgrounds/background_laptop.png
}

wallpaper {
    monitor = DP-5
    path = ~/.config/backgrounds/background_left.png
}

wallpaper {
    monitor = DP-6
    path = ~/.config/backgrounds/background_right.png
}
